title: "Claimed It, Now Explain It"
description: "A blog to verify technical skills beyond buzzwords."
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
  GitHub:
    - "https://github.com/claimed-it-now-explain-it"
